package codex

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jbeshir/demesne/internal/agents"
	proxyopenai "github.com/jbeshir/demesne/internal/proxies/openai"
)

// codexConfigBasename is the file WriteAgentConfig drops in the run's
// config dir. The runner mounts that dir read-only at
// agents.AgentConfigDir, so the in-sandbox path is codexConfigPath;
// the wrapper script copies it into CODEX_HOME before exec.
//
// The embedded wrapper script (codex-exec.sh) hardcodes the in-sandbox
// path agents.AgentConfigDir+"/config.toml" when copying this file into
// CODEX_HOME — keep the two in sync if the basename changes.
const codexConfigBasename = "config.toml"

// writeCodexConfig writes the Codex config.toml into configDir.
//
// model_provider and base_url MUST appear in the user-level CODEX_HOME
// config (they are ignored in project-local .codex/config.toml files);
// the wrapper points CODEX_HOME at a per-run directory and copies this
// file in, satisfying that requirement.
//
// approval_policy=never and sandbox_mode=danger-full-access give full-auto
// operation because we are already inside demesne's sandbox isolation.
//
// supports_websockets=false forces the HTTP/SSE path so the proxy can
// account usage via response-body inspection. The proxy ALSO handles
// WebSocket Upgrade, so this can be flipped to true later.
// UNVERIFIED: the flag may not reliably force SSE in all Codex versions.
func writeCodexConfig(configDir string, servers []agents.MCPServerInfo) error {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by demesne. model is supplied per-run via `codex exec -m`.\n")
	fmt.Fprintf(&b, "model_provider = %s\n", tomlString("demesne"))
	fmt.Fprintf(&b, "approval_policy = %s\n", tomlString("never"))
	fmt.Fprintf(&b, "sandbox_mode = %s\n", tomlString("danger-full-access"))
	fmt.Fprintf(&b, "\n")
	fmt.Fprintf(&b, "[model_providers.demesne]\n")
	fmt.Fprintf(&b, "name = %s\n", tomlString("demesne proxy"))
	fmt.Fprintf(&b, "base_url = %s\n", tomlString(proxyopenai.ListenURL()+"/v1"))
	fmt.Fprintf(&b, "wire_api = %s\n", tomlString("responses"))
	fmt.Fprintf(&b, "env_key = %s\n", tomlString(envAgentKey))
	fmt.Fprintf(&b, "supports_websockets = false\n")

	if len(servers) > 0 {
		fmt.Fprintf(&b, "\n")
		// UNVERIFIED: Codex HTTP-MCP config shape is unconfirmed. The exact
		// key name ("url" vs "transport" or "http") and the table structure
		// may need adjustment once Codex is installed and MCP-over-HTTP
		// support is confirmed. No-op cleanly when servers is empty.
		for _, s := range servers {
			fmt.Fprintf(&b, "[mcp_servers.%s]\n", s.Name)
			fmt.Fprintf(&b, "url = %s\n", tomlString(s.URL))
		}
	}

	path := filepath.Join(configDir, codexConfigBasename)
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// tomlString wraps s in TOML double-quote syntax, escaping backslashes
// and double quotes. Server names come from a trusted allowlist and URLs
// are loopback addresses, but we escape defensively anyway.
func tomlString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}
