#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const errors = [];
const fail = message => errors.push(message);
const root = path.resolve(process.argv[2] || '/out');
const gates = ['G1','G2','G3','G4','G5','G6','G7','G8'];
const states = new Set(['A','B','C','D','E']);
const scoreKeys = ['pain_magnitude_recurrence','evidence_strength','channel_accessibility','pilot_clarity','competitive_stagnation_whitespace','implementation_burden','continuing_manual_burden'];
const mechanismDimensions = ['customer_user','payer_authority','trigger_cadence','first_value_job_outcome','inputs_data_rights','workflow_output','acquisition_channel','economics_continuing_burden','dependencies_permissions_risk'];
const transitionVocabulary = new Set(['proposed','investigating','provisional-finalist','advance','evidence-insufficient','reject','dedup','supersede']);
const terminalTransitions = new Set(['advance','evidence-insufficient','reject','dedup','supersede']);
const legalNext = new Map([[null,new Set(['proposed'])],['proposed',new Set(['investigating','provisional-finalist','evidence-insufficient','reject','dedup','supersede'])],['investigating',new Set(['provisional-finalist','evidence-insufficient','reject','dedup','supersede'])],['provisional-finalist',new Set(['advance','evidence-insufficient','reject','dedup','supersede'])]]);
const read = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const sha = file => crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const exists = rel => fs.existsSync(path.join(root, rel));
const requireFile = rel => { const file=path.join(root,rel); if(!fs.existsSync(file)||!fs.statSync(file).isFile()||!fs.statSync(file).size) fail(`missing/empty file: ${rel}`); return file; };
const requireDir = rel => { const dir=path.join(root,rel); if(!fs.existsSync(dir)||!fs.statSync(dir).isDirectory()) fail(`missing directory: ${rel}`); return dir; };
const jsonLines = rel => {
  const file=requireFile(rel); if(!fs.existsSync(file)) return [];
  return fs.readFileSync(file,'utf8').split(/\r?\n/).filter(Boolean).map((line,i)=>{try{return JSON.parse(line)}catch{fail(`${rel}:${i+1}: malformed JSONL`);return null}}).filter(Boolean);
};
const safeArtifact = rel => typeof rel==='string' && rel.length && !path.isAbsolute(rel) && !rel.split(/[\\/]/).includes('..');
const validTime = value => typeof value==='string' && Number.isFinite(Date.parse(value));
const digestValue = value => crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
const matches=(value,schema)=>{if(schema.const!==undefined&&JSON.stringify(value)!==JSON.stringify(schema.const))return false;if(schema.enum&&!schema.enum.includes(value))return false;if(schema.properties&&value&&typeof value==='object')for(const[k,s]of Object.entries(schema.properties))if(k in value&&!matches(value[k],s))return false;return true;};
const schemaCheck=(value,schema,where)=>{ if(schema.const!==undefined&&JSON.stringify(value)!==JSON.stringify(schema.const))fail(`${where}: const schema failure`); if(schema.enum&&!schema.enum.includes(value))fail(`${where}: enum schema failure`); for(const branch of schema.allOf||[])schemaCheck(value,branch,where); if(schema.if&&matches(value,schema.if))schemaCheck(value,schema.then||{},where); if(schema.if&&!matches(value,schema.if)&&schema.else)schemaCheck(value,schema.else,where); if(schema.type==='object'){if(!value||typeof value!=='object'||Array.isArray(value)){fail(`${where}: object schema failure`);return;}for(const key of schema.required||[])if(!(key in value))fail(`${where}: missing ${key}`);for(const [key,sub] of Object.entries(schema.properties||{}))if(key in value)schemaCheck(value[key],sub,`${where}.${key}`);if(schema.additionalProperties===false)for(const key of Object.keys(value))if(!(key in (schema.properties||{})))fail(`${where}: unexpected ${key}`);} if(schema.type==='array'){if(!Array.isArray(value)){fail(`${where}: array schema failure`);return;}if(schema.minItems!==undefined&&value.length<schema.minItems)fail(`${where}: too few items`);if(schema.maxItems!==undefined&&value.length>schema.maxItems)fail(`${where}: too many items`);if(schema.uniqueItems&&new Set(value.map(JSON.stringify)).size!==value.length)fail(`${where}: duplicate items`);for(const [i,item] of value.entries())if(schema.items)schemaCheck(item,schema.items,`${where}[${i}]`);} if(schema.type==='string'){if(typeof value!=='string')fail(`${where}: string schema failure`);if(schema.minLength!==undefined&&value.length<schema.minLength)fail(`${where}: too short`);}if(schema.type==='integer'){if(!Number.isInteger(value))fail(`${where}: integer schema failure`);if(schema.minimum!==undefined&&value<schema.minimum)fail(`${where}: below minimum`);if(schema.maximum!==undefined&&value>schema.maximum)fail(`${where}: above maximum`);}if(schema.type==='boolean'&&typeof value!=='boolean')fail(`${where}: boolean schema failure`);if(schema.pattern&&typeof value==='string'&&!new RegExp(schema.pattern).test(value))fail(`${where}: pattern schema failure`);};
const applySchema=(name,value,where)=>schemaCheck(value,read(path.resolve(path.dirname(new URL(import.meta.url).pathname),`../schemas/${name}.schema.json`)),where);
const citationResolves=(cite,base='')=>{if(typeof cite!=='string')return false;const m=cite.match(/^(.*?):(?:L?(\d+)|record-([\w-]+))$/);if(!m)return false;const rel=m[1];const options=[path.join(root,rel),path.join(root,base,rel)];const file=options.find(p=>p.startsWith(root+path.sep)&&fs.existsSync(p)&&fs.statSync(p).isFile());if(!file)return false;const physical=fs.readFileSync(file,'utf8').split(/\r?\n/);if(m[2])return Number(m[2])>=1&&Number(m[2])<=physical.length;if(m[3]){for(const line of physical.filter(Boolean))try{const record=JSON.parse(line);if(record.record_id===m[3]||record.candidate_id===m[3])return true;}catch{}return false;}return false;};
const structuredRecordResolves=(cite,recordType,base='')=>{if(typeof cite!=='string')return false;const m=cite.match(/^(.*?):record-([\w-]+)$/);if(!m)return false;const options=[path.join(root,m[1]),path.join(root,base,m[1])],file=options.find(p=>p.startsWith(root+path.sep)&&fs.existsSync(p)&&fs.statSync(p).isFile());if(!file)return false;for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/).filter(Boolean))try{const record=JSON.parse(line);if(record.record_id===m[2]&&record.record_type===recordType)return true;}catch{}return false;};
const walkJsonl=dir=>fs.existsSync(dir)?fs.readdirSync(dir,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?walkJsonl(path.join(dir,entry.name)):entry.isFile()&&entry.name.endsWith('.jsonl')?[path.join(dir,entry.name)]:[]):[];

try {
  for (const rel of ['run-spec.json','gate-contract.json','execution-ledger.jsonl','candidates.jsonl','rejection-ledger.jsonl','selection-transitions.jsonl','archive/inventory.json','archive/comparisons.json','archive/novelty-decisions.jsonl','aggregate/diversity-matrix.json','catalog.json','handoff-manifest.json','bundle-manifest.json','REPORT.md','SUMMARY.md']) requireFile(rel);
  for (const rel of ['raw','territories','archive','aggregate','reports','finalists','selected','failures/quarantine']) requireDir(rel);
  const contractPath=path.join(root,'gate-contract.json'); const contract=read(contractPath);
  const canonicalContract=path.resolve(path.dirname(new URL(import.meta.url).pathname),'../assets/gate-contract-v1.json');
  if(sha(contractPath)!==sha(canonicalContract)) fail('gate-contract.json differs from bundled frozen contract');
  if(contract.contract_version!=='1.0.0'||contract.unit_of_analysis!=='first-value-workflow') fail('invalid contract identity');
  if(JSON.stringify(contract.evidence_states)!==JSON.stringify(['A','B','C','D','E'])) fail('invalid evidence states');
  if(JSON.stringify(contract.gates)!==JSON.stringify(gates)) fail('contract must contain ordered G1-G8');
  if(!Array.isArray(contract.gate_definitions)||new Set(contract.gate_definitions.map(x=>x.id)).size!==8||!gates.every(g=>contract.gate_definitions.some(x=>x.id===g))) fail('contract must define each gate exactly once');
  if(!Array.isArray(contract.hard_red_lines)||contract.hard_red_lines.length!==6) fail('contract must define six hard red lines');
  if(JSON.stringify(Object.keys(contract.scoring||{}).sort())!==JSON.stringify([...scoreKeys].sort())||Object.values(contract.scoring||{}).reduce((a,b)=>a+b,0)!==100) fail('invalid scoring contract');
  if(contract.targeted_job_limits?.round_1!==4||contract.targeted_job_limits?.round_2!==2||contract.targeted_job_limits?.total!==6||contract.retry_limit!==1||contract.unknown_is_disconfirmation!==false) fail('invalid bounds or unknown policy');
  applySchema('gate-contract',contract,'gate-contract.json');
  const spec=read(path.join(root,'run-spec.json')); if(spec.contract_sha256!==sha(contractPath)) fail('run-spec contract SHA-256 mismatch'); if(!Array.isArray(spec.raw_sources)||!spec.raw_sources.length)fail('run-spec raw_sources missing');for(const source of spec.raw_sources||[]){if(!source.original_path||!safeArtifact(source.delivered_path)||!source.sha256)fail('invalid raw source provenance');else{const file=requireFile(source.delivered_path);if(fs.existsSync(file)&&sha(file)!==source.sha256)fail(`raw source hash mismatch: ${source.delivered_path}`);}}
  const manifest=read(path.join(root,'handoff-manifest.json'));
  if(manifest.schema_version!=='1.0.0'||manifest.contract_sha256!==sha(contractPath)) fail('manifest identity/hash mismatch');
  if(manifest.next_skill!=='sandbox-hypothesis-stress-test'||manifest.mount_one_brief_per_run!==true) fail('downstream one-brief handoff policy missing');
  applySchema('handoff-manifest',manifest,'handoff-manifest.json');
  if(!Array.isArray(manifest.finalists)||!manifest.finalists.length) fail('finalists must be nonempty');
  const ledger=jsonLines('execution-ledger.jsonl');
  for(const [i,entry] of ledger.entries()) { if(!entry.artifact||!entry.action||!entry.status) fail(`execution ledger ${i+1}: missing artifact/action/status`); if(entry.execution_mode==='child'&&(!entry.job_id||entry.terminal_status!=='succeeded'||entry.exit_code!==0||!/^gpt-/.test(entry.model||'')||entry.no_descendant_delegation!==true)) fail(`execution ledger ${i+1}: child acceptance contract invalid`); if(entry.status==='accepted'&&entry.attempt>2) fail(`execution ledger ${i+1}: retry limit exceeded`);if(entry.status==='accepted'&&entry.sha256&&safeArtifact(entry.artifact)){const file=requireFile(entry.artifact);if(fs.existsSync(file)&&sha(file)!==entry.sha256)fail(`execution ledger ${i+1}: artifact hash mismatch`);} }
  const findingByClaimId=new Map();
  for(const file of [...walkJsonl(path.join(root,'territories')),...walkJsonl(path.join(root,'finalists')).filter(x=>x.includes(`${path.sep}avenues${path.sep}`))]) {
    const rel=path.relative(root,file);for(const [i,f] of fs.readFileSync(file,'utf8').split(/\r?\n/).filter(Boolean).map(JSON.parse).entries()){
      if(!f.claim_id||!f.candidate_id||!f.evidence_state)continue;applySchema('finding',f,`${rel}:${i+1}`);if(['A','B','C','D'].includes(f.evidence_state)&&!(f.citations||[]).length)fail(`${rel}:${i+1}: ${f.evidence_state} finding requires resolving citation`);if(['A','B','C'].includes(f.evidence_state)&&f.evidence_basis!=='investigative-result')fail(`${rel}:${i+1}: investigative finding basis mismatch`);if(f.evidence_state==='D'&&!['investigative-result','attempt-history-record','absence-of-attempt-record'].includes(f.evidence_basis))fail(`${rel}:${i+1}: D finding basis is not structured`);if(f.evidence_state==='D'&&f.evidence_basis!=='investigative-result'){const expected=f.evidence_basis==='attempt-history-record'?'attempt-history':'absence-of-attempt';if(!(f.citations||[]).some(cite=>structuredRecordResolves(cite,expected,path.dirname(rel))))fail(`${rel}:${i+1}: ${f.evidence_basis} must cite a matching structured record`);}
      if(findingByClaimId.has(f.claim_id))fail(`duplicate finding claim ID: ${f.claim_id}`);else findingByClaimId.set(f.claim_id,{...f,rel});
      for(const cite of f.citations||[])if(!citationResolves(cite,path.dirname(rel)))fail(`${rel}:${i+1}: unresolved finding citation ${cite}`);
    }
  }
  const checkClaimRefs=(where,candidateId,claimIds,citations,gate=null,evidenceBasis=null)=>{const cited=new Set(citations||[]);for(const claimId of claimIds||[]){const finding=findingByClaimId.get(claimId);if(!finding){fail(`${where}: finding claim ID does not resolve: ${claimId}`);continue;}if(finding.candidate_id!==candidateId)fail(`${where}: finding claim ${claimId} belongs to another candidate`);if(gate&&!(finding.assigned_gates||[]).includes(gate))fail(`${where}: finding claim ${claimId} is not assigned to ${gate}`);if(evidenceBasis&&finding.evidence_basis!==evidenceBasis)fail(`${where}: evidence basis disagrees with finding claim ${claimId}`);if(!(finding.citations||[]).some(cite=>cited.has(cite)))fail(`${where}: citations do not agree with finding claim ${claimId}`);}};
  const candidates=jsonLines('candidates.jsonl'); const candidateIds=candidates.map(c=>c.candidate_id);if(new Set(candidateIds).size!==candidateIds.length)fail('candidate IDs must be unique before indexing');const candidateById=new Map();
  for(const [i,c] of candidates.entries()) {
    if(!c.candidate_id||!c.customer||!c.payer||!c.trigger_event||!c.first_value_workflow||!Array.isArray(c.citations)||!c.citations.length) fail(`candidate ${i+1}: required fields/citations missing`);
    if(JSON.stringify(Object.keys(c.scores||{}).sort())!==JSON.stringify([...scoreKeys].sort())) fail(`${c.candidate_id||i}: score dimensions differ from contract`);
    for(const [k,v] of Object.entries(c.scores||{})) if(!Number.isInteger(v)||v<0||v>5) fail(`${c.candidate_id}: invalid ${k} score`);
    for(const key of scoreKeys){const basis=c.score_basis?.[key];if(!basis||!Array.isArray(basis.claim_ids)||!basis.claim_ids.length||!Array.isArray(basis.citations))fail(`${c.candidate_id}: ${key} score lacks claim-linked basis`);for(const cite of basis?.citations||[])if(!citationResolves(cite))fail(`${c.candidate_id}: unresolved score citation ${cite}`);checkClaimRefs(`${c.candidate_id}: ${key} score`,c.candidate_id,basis?.claim_ids,basis?.citations);}
    const stagnationRanges={unknown:[0,0],'absence-only':[0,1],'exact-job-mismatch':[2,3],'longitudinal-unresolved':[4,5]},range=stagnationRanges[c.competitive_stagnation?.basis_class],stagnation=c.scores?.competitive_stagnation_whitespace;if(!range||stagnation<range[0]||stagnation>range[1])fail(`${c.candidate_id}: competitive stagnation score outside evidence anchor range`);if(stagnation>0&&(!(c.competitive_stagnation?.claim_ids||[]).length||!(c.competitive_stagnation?.citations||[]).length))fail(`${c.candidate_id}: competitive stagnation evidence unsupported`);if((c.competitive_stagnation?.claim_ids||[]).length&&c.competitive_stagnation?.citations?.length)checkClaimRefs(`${c.candidate_id}: competitive stagnation`,c.candidate_id,c.competitive_stagnation.claim_ids,c.competitive_stagnation.citations);
    for(const [dimension,barrier] of Object.entries(c.barrier_decomposition||{})){if(!barrier||typeof barrier!=='object'||!barrier.assessment||!(barrier.claim_ids||[]).length||!Array.isArray(barrier.citations)||typeof barrier.strong_builder_prior_applied!=='boolean'||!('hard_red_line_id' in barrier))fail(`${c.candidate_id}: barrier ${dimension} lacks structured prior/red-line evidence`);if(barrier?.strong_builder_prior_applied&&dimension!=='build_complexity')fail(`${c.candidate_id}: strong-builder prior may apply only to build_complexity`);if(barrier?.hard_red_line_id!==null&&!contract.hard_red_lines.includes(barrier?.hard_red_line_id))fail(`${c.candidate_id}: barrier hard red line is not frozen/enumerated`);for(const cite of barrier?.citations||[])if(!citationResolves(cite))fail(`${c.candidate_id}: unresolved barrier citation ${cite}`);checkClaimRefs(`${c.candidate_id}: barrier ${dimension}`,c.candidate_id,barrier?.claim_ids,barrier?.citations);}
    const computed=Math.round(scoreKeys.reduce((sum,key)=>sum+(c.scores?.[key]||0)*contract.scoring[key]/5,0)); if(c.normalized_score!==undefined&&c.normalized_score!==computed) fail(`${c.candidate_id}: normalized score mismatch`); candidateById.set(c.candidate_id,{...c,computed});
    applySchema('candidate',c,`candidates.jsonl:${i+1}`); for(const cite of c.citations||[])if(!citationResolves(cite))fail(`${c.candidate_id}: unresolved candidate citation ${cite}`);
  }
  const inventory=read(path.join(root,'archive/inventory.json'));applySchema('archive-inventory',inventory,'archive/inventory.json');const inventoryIds=(inventory.records||[]).map(x=>x.archive_candidate_id);if(new Set(inventoryIds).size!==inventoryIds.length)fail('archive inventory stable IDs must be unique');if(inventory.archive_mounted!==spec.archive_mounted)fail('archive inventory mounted status disagrees with run-spec');const expectedInventoryDigest=digestValue(inventory.records||[]);if(inventory.inventory_digest!==expectedInventoryDigest)fail('archive inventory digest mismatch');if(inventory.archive_mounted&&!inventoryIds.length)fail('mounted archive inventory must be nonempty');for(const record of inventory.records||[]){if(!safeArtifact(record.source_path))fail(`unsafe archive source path: ${record.source_path}`);else{const source=requireFile(record.source_path);if(fs.existsSync(source)&&sha(source)!==record.source_sha256)fail(`archive source hash mismatch: ${record.archive_candidate_id}`);}}
  const comparisons=read(path.join(root,'archive/comparisons.json')); applySchema('archive-comparison',comparisons,'archive/comparisons.json');
  if(JSON.stringify(comparisons.dimensions)!==JSON.stringify(mechanismDimensions))fail('archive comparison must use all nine ordered mechanism dimensions');
  if(new Set((comparisons.comparisons||[]).map(x=>x.candidate_id)).size!==candidateById.size||[...candidateById.keys()].some(id=>!(comparisons.comparisons||[]).some(x=>x.candidate_id===id)))fail('archive comparison must cover every candidate before ranking');
  if(comparisons.archive_mounted!==inventory.archive_mounted)fail('archive comparison mounted status disagrees with inventory');
  const comparisonById=new Map();for(const item of comparisons.comparisons||[]){if(comparisonById.has(item.comparison_id))fail('archive comparison IDs must be unique');comparisonById.set(item.comparison_id,item);if(item.inventory_digest!==inventory.inventory_digest)fail(`${item.candidate_id}: comparison inventory digest mismatch`);if(JSON.stringify(Object.keys(item.dimension_results||{}).sort())!==JSON.stringify([...mechanismDimensions].sort()))fail(`${item.candidate_id}: candidate comparison lacks nine dimensions`);const neighborIds=(item.neighbors||[]).map(n=>n.archive_candidate_id);if(JSON.stringify([...neighborIds].sort())!==JSON.stringify([...inventoryIds].sort()))fail(`${item.candidate_id}: comparison must account for every archive inventory record`);const minimum=Math.min(...(item.neighbors||[]).map(n=>n.distance));for(const n of item.neighbors||[]){if(JSON.stringify(Object.keys(n.dimension_results||{}).sort())!==JSON.stringify([...mechanismDimensions].sort()))fail(`${item.candidate_id}: neighbor comparison lacks nine dimensions`);if(n.is_nearest!==(n.distance===minimum))fail(`${item.candidate_id}: deterministic nearest-neighbor marker mismatch`);}}
  const novelty=jsonLines('archive/novelty-decisions.jsonl'); let priorDigest=null;const noveltyRecordIds=new Set();for(const [i,n] of novelty.entries()){applySchema('novelty-decision',n,`archive/novelty-decisions.jsonl:${i+1}`);if(noveltyRecordIds.has(n.record_id))fail('novelty decision record IDs must be unique');noveltyRecordIds.add(n.record_id);if(n.sequence!==i+1||n.prior_decision_digest!==priorDigest)fail('novelty decision ledger is not append-only/digest-linked');priorDigest=digestValue(n);const comparison=comparisonById.get(n.comparison_ref);if(!comparison||comparison.candidate_id!==n.candidate_id)fail(`${n.candidate_id}: novelty comparison_ref does not resolve`);if(n.inventory_digest!==inventory.inventory_digest)fail(`${n.candidate_id}: novelty inventory digest mismatch`);const expectedNeighbors=(comparison?.neighbors||[]).filter(x=>x.is_nearest).map(x=>x.archive_candidate_id).sort();if(JSON.stringify([...(n.neighbors||[])].sort())!==JSON.stringify(expectedNeighbors))fail(`${n.candidate_id}: novelty neighbors differ from deterministic nearest neighbors`);if(!inventory.archive_mounted&&(n.outcome!=='keep'||n.neighbors.length))fail(`${n.candidate_id}: no-archive novelty outcome must be keep with no neighbors`);}
  if([...candidateById.keys()].some(id=>!novelty.some(n=>n.candidate_id===id)))fail('append-only novelty decisions must cover every candidate');
  const transitions=jsonLines('selection-transitions.jsonl');const transitionIds=new Set();for(const [i,t] of transitions.entries()){applySchema('selection-transition',t,`selection-transitions.jsonl:${i+1}`);if(transitionIds.has(t.record_id))fail('selection transition record IDs must be unique');transitionIds.add(t.record_id);if(!validTime(t.occurred_at))fail(`${t.candidate_id}: invalid transition timestamp`);if(!transitionVocabulary.has(t.to)&&!(spec.selection_vocabulary_extensions||[]).includes(t.to))fail(`${t.candidate_id}: undeclared selection transition outcome`);for(const cite of t.citations||[])if(!citationResolves(cite))fail(`${t.candidate_id}: unresolved transition citation ${cite}`);checkClaimRefs(`${t.candidate_id}: selection transition ${t.record_id}`,t.candidate_id,t.claim_ids,t.citations);}
  for(const id of candidateById.keys()){const chain=transitions.filter(t=>t.candidate_id===id);for(let i=0;i<chain.length;i++){const expectedFrom=i?chain[i-1].to:null;if(chain[i].from!==expectedFrom)fail(`${id}: broken selection transition state chain`);if(i&&Date.parse(chain[i].occurred_at)<Date.parse(chain[i-1].occurred_at))fail(`${id}: selection transitions are not causally ordered`);if(!legalNext.get(chain[i].from)?.has(chain[i].to)&&!(spec.selection_vocabulary_extensions||[]).includes(chain[i].to))fail(`${id}: illegal selection transition ${chain[i].from} -> ${chain[i].to}`);}}
  if([...candidateById.keys()].some(id=>!transitions.some(t=>t.candidate_id===id)))fail('every candidate requires a contemporaneous selection transition');
  const diversity=read(path.join(root,'aggregate/diversity-matrix.json'));applySchema('diversity-matrix',diversity,'aggregate/diversity-matrix.json');if(JSON.stringify(diversity.dimensions)!==JSON.stringify(mechanismDimensions))fail('diversity matrix must use all nine ordered mechanism dimensions');
  const pairKeys=new Set();for(const pair of diversity.pairs||[]){if(pair.candidate_a===pair.candidate_b||!candidateById.has(pair.candidate_a)||!candidateById.has(pair.candidate_b))fail('diversity pair identities must be distinct known candidates');const key=[pair.candidate_a,pair.candidate_b].sort().join('\u0000');if(pairKeys.has(key))fail('diversity candidate pairs must be unique');pairKeys.add(key);if((pair.identical_dimensions||[]).some(d=>!mechanismDimensions.includes(d)))fail('diversity pair contains unknown mechanism dimension');if(pair.adjacent!==(pair.identical_dimensions?.length>=diversity.adjacency_threshold))fail('diversity adjacency does not match threshold');if(pair.adjacent&&pair.disposition==='retain')fail('retained adjacent pair requires explicit waiver');if(pair.disposition==='waiver'){if(!pair.waiver_reason||(pair.mechanism_delta_dimensions||[]).some(d=>!mechanismDimensions.includes(d)||(pair.identical_dimensions||[]).includes(d))||!(pair.evidence_claim_ids||[]).length||!(pair.evidence_citations||[]).length)fail('diversity waiver requires evidence-backed distinct mechanism delta');for(const cite of pair.evidence_citations||[])if(!citationResolves(cite))fail(`diversity waiver unresolved citation ${cite}`);for(const id of [pair.candidate_a,pair.candidate_b])checkClaimRefs(`diversity waiver ${key}`,id,(pair.evidence_claim_ids||[]).filter(claim=>findingByClaimId.get(claim)?.candidate_id===id),pair.evidence_citations);}}
  const catalog=read(path.join(root,'catalog.json'));applySchema('catalog',catalog,'catalog.json');
  if(catalog.integration_status==='integrated'){if(!(spec.integration_authorized===true&&spec.integration_contract?.path&&spec.integration_contract?.sha256&&spec.integration_completion_path))fail('integration claim requires authorization, contract, and completion ledger');else{for(const [kind,rel,expected] of [['contract',spec.integration_contract.path,spec.integration_contract.sha256],['completion',spec.integration_completion_path,null]]){if(!safeArtifact(rel)){fail(`unsafe integration ${kind} path`);continue;}const file=requireFile(rel);if(expected&&fs.existsSync(file)&&sha(file)!==expected)fail(`integration ${kind} hash mismatch`);}if(safeArtifact(spec.integration_completion_path)&&exists(spec.integration_completion_path)){const completion=read(path.join(root,spec.integration_completion_path));applySchema('integration-contract',completion,spec.integration_completion_path);if(completion.contract_path!==spec.integration_contract.path||completion.contract_sha256!==spec.integration_contract.sha256)fail('integration completion contract linkage mismatch');for(const action of completion.actions||[]){if(!safeArtifact(action.artifact_path))fail('unsafe completed integration artifact path');else{const file=requireFile(action.artifact_path);if(fs.existsSync(file)&&sha(file)!==action.artifact_sha256)fail(`completed integration action hash mismatch: ${action.action_id}`);}}}}}
  if(new Set((catalog.candidates||[]).map(x=>x.candidate_id)).size!==candidateById.size||[...candidateById.keys()].some(id=>!(catalog.candidates||[]).some(x=>x.candidate_id===id)))fail('catalog must map every candidate');
  for(const entry of catalog.candidates||[]){if((entry.external_identities||[]).some(x=>candidateById.has(x.value)))fail(`${entry.candidate_id}: external identity collides with fresh run candidate ID`);if(!safeArtifact(entry.report_path)){fail(`${entry.candidate_id}: unsafe report path`);continue;}const report=requireFile(entry.report_path);if(fs.existsSync(report)&&sha(report)!==entry.report_sha256)fail(`${entry.candidate_id}: catalog report hash mismatch`);const chain=transitions.filter(t=>t.candidate_id===entry.candidate_id);if(!chain.length||chain.at(-1).to!==entry.disposition||!terminalTransitions.has(chain.at(-1).to))fail(`${entry.candidate_id}: catalog disposition disagrees with final selection transition`);if(!safeArtifact(entry.report_attestation_path)){fail(`${entry.candidate_id}: unsafe report attestation path`);continue;}const attestation=read(requireFile(entry.report_attestation_path));applySchema('report-attestation',attestation,entry.report_attestation_path);if(attestation.candidate_id!==entry.candidate_id||attestation.report_path!==entry.report_path)fail(`${entry.candidate_id}: report attestation identity mismatch`);if((attestation.transition_record_ids||[]).some(x=>!chain.some(t=>t.record_id===x)))fail(`${entry.candidate_id}: report attestation transition does not resolve`);for(const [section,refs] of Object.entries(attestation.sections||{}))if(!Array.isArray(refs)||!refs.length||refs.some(ref=>!citationResolves(ref)))fail(`${entry.candidate_id}: report attestation section ${section} lacks resolvable evidence`);checkClaimRefs(`${entry.candidate_id}: report attestation`,entry.candidate_id,attestation.finding_ids,[...new Set((attestation.finding_ids||[]).flatMap(x=>findingByClaimId.get(x)?.citations||[]))]);}
  const seenFinalists=new Set();
  for(const finalist of manifest.finalists||[]) {
    const id=finalist.candidate_id; if(!id||seenFinalists.has(id)) { fail('missing/duplicate finalist id'); continue; } seenFinalists.add(id);
    const base=`finalists/${id}`; const indexPath=requireFile(`${base}/index.json`); requireFile(`${base}/problem-report.md`); requireFile(`${base}/reviews/initial.json`); requireFile(`${base}/reviews/post-round-1.json`); requireDir(`${base}/avenues`); requireDir(`${base}/reviews`); requireDir(`${base}/gap-plans`); requireDir(`${base}/attempts`);
    if(!candidateById.has(id)) fail(`${id}: finalist missing from candidates.jsonl`); const candidate=candidateById.get(id);
    if(fs.existsSync(indexPath)){const index=read(indexPath); if(index.candidate_id!==id||index.contract_sha256!==sha(contractPath)||!Number.isInteger(index.normalized_score)||index.normalized_score!==candidate?.computed) fail(`${id}: invalid finalist index/score/hash`);}
    const covered=new Set(); for(const lane of ['customer','market','competitor','technical','risk']) { const rel=`${base}/avenues/${lane}.jsonl`; const findings=jsonLines(rel); if(!findings.length) fail(`${id}/${lane}: no findings`); for(const f of findings){if(f.candidate_id!==id||f.lane!==lane)fail(`${rel}: finding identity failure`);for(const g of f.assigned_gates||[])covered.add(g);if(f.round>0){const reviewRel=`${base}/reviews/${f.round===1?'initial':'post-round-1'}.json`,reviewHash=exists(reviewRel)?sha(path.join(root,reviewRel)):null,reviewEntry=ledger.find(x=>x.artifact===reviewRel&&x.action==='independent-review'&&x.status==='accepted'),acceptance=ledger.find(x=>x.action==='finding-acceptance'&&x.candidate_id===id&&x.claim_id===f.claim_id&&x.status==='accepted');if(!reviewEntry||!acceptance||acceptance.source_review_sha256!==reviewHash||!validTime(acceptance.accepted_at)||Date.parse(acceptance.accepted_at)<=Date.parse(reviewEntry.accepted_at))fail(`${id}/${f.claim_id}: targeted finding acceptance lacks post-review temporal provenance`);}} } if(!gates.every(g=>covered.has(g))) fail(`${id}: lane findings do not cover every assigned gate G1-G8`);
    for(const stage of ['initial','post-round-1']){const rel=`${base}/reviews/${stage}.json`,review=read(path.join(root,rel)),reviewGates=(review.cells||[]).map(c=>c.gate);applySchema('gate-review',review,rel);if(review.contract_sha256!==sha(contractPath)||reviewGates.length!==8||new Set(reviewGates).size!==8||!gates.every(g=>reviewGates.includes(g)))fail(`${id}: ${stage} review must contain exactly G1-G8`);for(const cell of review.cells||[]){if(['A','B','C','D'].includes(cell.state)&&!(cell.citations||[]).length)fail(`${id}/${cell.gate}: gate state ${cell.state} requires resolving citation`);for(const cite of cell.citations||[])if(!citationResolves(cite,base))fail(`${id}/${cell.gate}: unresolvable citation ${cite}`);checkClaimRefs(`${id}/${cell.gate} gate`,id,cell.claim_ids,cell.citations,cell.gate,cell.evidence_basis);}}
    const finalReviewPath=`${base}/reviews/final.json`; requireFile(finalReviewPath);
    if(exists(finalReviewPath)) {
      const review=read(path.join(root,finalReviewPath)); const reviewGates=(review.cells||[]).map(c=>c.gate);
      applySchema('gate-review',review,finalReviewPath);
      if(review.contract_sha256!==sha(contractPath)||reviewGates.length!==8||new Set(reviewGates).size!==8||!gates.every(g=>reviewGates.includes(g))) fail(`${id}: final review must contain exactly G1-G8`);
      for(const cell of review.cells||[]) { if(!states.has(cell.state)||!cell.basis) fail(`${id}/${cell.gate}: invalid state/basis`);if(['A','B','C','D'].includes(cell.state)&&!(cell.citations||[]).length)fail(`${id}/${cell.gate}: gate state ${cell.state} requires resolving citation`); for(const cite of cell.citations||[]) if(!citationResolves(cite,base)) fail(`${id}/${cell.gate}: unresolvable citation ${cite}`);checkClaimRefs(`${id}/${cell.gate} gate`,id,cell.claim_ids,cell.citations,cell.gate,cell.evidence_basis); }
      if(review.normalized_score!==undefined&&review.normalized_score!==candidate?.computed)fail(`${id}: review/candidate score mismatch`);if(review.decision!==finalist.decision) fail(`${id}: review/manifest decision mismatch`); for(const cell of review.cells||[]) if(finalist.evidence_vector?.[cell.gate]!==cell.state) fail(`${id}/${cell.gate}: manifest/review state mismatch`); if(JSON.stringify(review.hard_red_line_findings||[])!==JSON.stringify(finalist.hard_red_line_findings||[])) fail(`${id}: hard-red-line findings mismatch`);
    }
    const actual={round_1:0,round_2:0}; for(const round of [1,2]) { const rel=`${base}/gap-plans/round-${round}.json`; requireFile(rel); if(exists(rel)){const plan=read(path.join(root,rel));applySchema('gap-plan',plan,rel);const jobs=plan.jobs||[]; actual[`round_${round}`]=jobs.length;const expectedReview=`${base}/reviews/${round===1?'initial':'post-round-1'}.json`; if(plan.candidate_id!==id||plan.contract_sha256!==sha(contractPath)||plan.round!==round||plan.source_review_path!==expectedReview||!exists(expectedReview)||plan.source_review_sha256!==sha(path.join(root,expectedReview))||jobs.length>(round===1?4:2)) fail(`${id}: round-${round} plan identity/hash/review provenance/budget invalid`);for(const job of jobs)if(!/^gpt-/.test(job.model||'')||job.no_descendant_delegation!==true)fail(`${id}: invalid targeted job contract`);} }
    if(!['advance','evidence-insufficient','reject'].includes(finalist.decision)) fail(`${id}: invalid decision`);if((catalog.candidates||[]).find(x=>x.candidate_id===id)?.disposition!==finalist.decision)fail(`${id}: catalog/finalist disposition mismatch`);if(typeof finalist.reevaluated!=='boolean')fail(`${id}: missing reevaluated status`);
    if(!finalist.evidence_vector||Object.keys(finalist.evidence_vector).sort().join(',')!==gates.join(',')||gates.some(g=>!states.has(finalist.evidence_vector[g]))) fail(`${id}: evidence vector must contain exactly G1-G8`);
    if((finalist.targeted_jobs?.round_1??99)>4||(finalist.targeted_jobs?.round_2??99)>2) fail(`${id}: targeted job budget exceeded`);
    if(finalist.targeted_jobs?.round_1!==actual.round_1||finalist.targeted_jobs?.round_2!==actual.round_2) fail(`${id}: manifest/plan targeted job counts mismatch`);
    if((finalist.unresolved_gaps||[]).some(gap=>typeof gap!=='string'||!gap.trim()||gap.includes('[object Object]'))) fail(`${id}: malformed unresolved gap`);
    if(!Array.isArray(finalist.hard_red_line_findings)) fail(`${id}: hard_red_line_findings must be an array`);
    for(const [kind,rel,expected] of [['report',finalist.report_path,finalist.report_sha256],...(finalist.decision==='advance'?[['brief',finalist.brief_path,finalist.brief_sha256]]:[])]) { if(!safeArtifact(rel)){fail(`${id}: unsafe ${kind} path`);continue;} const file=requireFile(rel); if(fs.existsSync(file)&&sha(file)!==expected) fail(`${id}: ${kind} SHA-256 mismatch`); }
    const catalogEntry=(catalog.candidates||[]).find(x=>x.candidate_id===id);if(catalogEntry&&safeArtifact(catalogEntry.report_attestation_path)){const attestation=read(path.join(root,catalogEntry.report_attestation_path));if(!attestation.finalist_sections)fail(`${id}: finalist report requires richer structured attestations`);else for(const [section,refs] of Object.entries(attestation.finalist_sections))if(!Array.isArray(refs)||!refs.length||refs.some(ref=>!citationResolves(ref)))fail(`${id}: finalist report attestation section ${section} lacks resolvable evidence`);}
    if(finalist.decision!=='advance'&&(finalist.brief_path||finalist.brief_sha256))fail(`${id}: only advancing candidates may have briefs`);if(finalist.decision==='advance'&&(!finalist.reevaluated||candidate.computed<contract.default_selection_policy.minimum_score||finalist.hard_red_line_findings.length||['G6','G7','G8'].some(g=>finalist.evidence_vector[g]!=='A')||Object.values(finalist.evidence_vector).includes('E'))) fail(`${id}: advance/brief violates frozen decision policy or reevaluation requirement`);
  }
  const finalistIds=[...(manifest.finalists||[])].map(x=>x.candidate_id);for(let i=0;i<finalistIds.length;i++)for(let j=i+1;j<finalistIds.length;j++)if(!(diversity.pairs||[]).some(p=>new Set([p.candidate_a,p.candidate_b]).size===2&&[p.candidate_a,p.candidate_b].includes(finalistIds[i])&&[p.candidate_a,p.candidate_b].includes(finalistIds[j])))fail(`diversity matrix missing finalist pair ${finalistIds[i]}/${finalistIds[j]}`);
  for(const id of finalistIds){const stages=[['initial',null],['post-round-1','initial'],['final','post-round-1']];let lastAccepted=-Infinity;for(const [stage] of stages){const artifact=`finalists/${id}/reviews/${stage}.json`,entry=ledger.find(x=>x.artifact===artifact&&x.action==='independent-review'&&x.status==='accepted');if(!entry||entry.producer_role!=='independent-reviewer'||entry.independence_attested!==true||!validTime(entry.accepted_at))fail(`${id}: ${stage} review lacks independent temporal provenance`);else{const accepted=Date.parse(entry.accepted_at);if(accepted<lastAccepted)fail(`${id}: review stages are out of temporal order`);lastAccepted=accepted;const reviewHash=sha(path.join(root,artifact));if(entry.sha256!==reviewHash)fail(`${id}: review provenance hash mismatch`);const sourcedJobs=ledger.filter(x=>x.action==='gap-job'&&x.candidate_id===id&&x.source_review_sha256===reviewHash);if(stage!=='final'&&sourcedJobs.some(x=>!validTime(x.started_at)||Date.parse(x.started_at)<=accepted))fail(`${id}: gap job occurred before its source review was accepted`);}}
  }
  const bundle=read(path.join(root,'bundle-manifest.json'));applySchema('bundle-manifest',bundle,'bundle-manifest.json');if(bundle.contract_sha256!==sha(contractPath)||bundle.catalog_path!=='catalog.json'||bundle.catalog_sha256!==sha(path.join(root,'catalog.json')))fail('bundle contract/catalog hash mismatch');for(const item of bundle.artifacts||[]){if(!safeArtifact(item.path)){fail('unsafe bundle artifact path');continue;}const file=requireFile(item.path);if(fs.existsSync(file)&&sha(file)!==item.sha256)fail(`bundle artifact hash mismatch: ${item.path}`);}
  if(errors.length) { for(const error of errors) console.error(`INVALID: ${error}`); process.exitCode=1; } else console.log('VALID');
} catch (error) { console.error(`INVALID: ${error.message}`); process.exitCode=1; }
