#!/usr/bin/env node
import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import crypto from 'node:crypto'; import {spawnSync} from 'node:child_process';
const here=path.dirname(new URL(import.meta.url).pathname), skill=path.resolve(here,'..'), validator=path.join(skill,'scripts/validate.mjs');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'); const put=(root,rel,data='fixture\n')=>{const p=path.join(root,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,data);};
function fixture(mutator){const root=fs.mkdtempSync(path.join(os.tmpdir(),'problem-discovery-')); const id='example'; fs.cpSync(path.join(skill,'assets/gate-contract-v1.json'),path.join(root,'gate-contract.json')); const contractHash=hash(path.join(root,'gate-contract.json'));
  put(root,'raw/source','fixture source\n'); put(root,'run-spec.json',JSON.stringify({contract_sha256:contractHash,output_path:root,raw_sources:[{original_path:'/fixture/source',delivered_path:'raw/source',sha256:hash(path.join(root,'raw/source'))}]})); put(root,'execution-ledger.jsonl',JSON.stringify({artifact:'gate-contract.json',action:'freeze',status:'accepted',attempt:1,execution_mode:'local-copy'})+'\n'); put(root,'rejection-ledger.jsonl','{}\n');
  const scores={pain_magnitude_recurrence:0,evidence_strength:0,channel_accessibility:0,pilot_clarity:0,competitive_stagnation_whitespace:0,implementation_burden:0,continuing_manual_burden:0}; put(root,'candidates.jsonl',JSON.stringify({candidate_id:id,territory:'fixture',customer:'c',payer:'p',trigger_event:'t',problem:'p',first_value_workflow:'w',citations:['raw/source:L1'],scores})+'\n');
  for(const d of ['territories','aggregate','selected','failures/quarantine',`finalists/${id}/attempts`])fs.mkdirSync(path.join(root,d),{recursive:true}); for(const f of ['REPORT.md','SUMMARY.md',`finalists/${id}/problem-report.md`])put(root,f);
  put(root,`finalists/${id}/index.json`,JSON.stringify({candidate_id:id,contract_sha256:contractHash,normalized_score:0})); const laneGates={customer:['G4','G6','G7','G8'],market:['G4','G6','G7','G8'],competitor:['G2','G8'],technical:['G1','G2','G5'],risk:['G3','G4','G5']}; for(const lane of Object.keys(laneGates))put(root,`finalists/${id}/avenues/${lane}.jsonl`,JSON.stringify({candidate_id:id,lane,proposition:'test proposition',assigned_gates:laneGates[lane],attempts:['offline check'],sources_consulted:['fixture'],citations:[],evidence_state:'C',evidence_found:'',missing_proposition:'missing',round:0})+'\n');
  const cells=['G1','G2','G3','G4','G5','G6','G7','G8'].map(g=>({gate:g,state:'C',basis:'unknown',citations:[],missing_proposition:'missing'})); put(root,`finalists/${id}/reviews/final.json`,JSON.stringify({candidate_id:id,contract_sha256:contractHash,cells,decision:'evidence-insufficient',hard_red_line_findings:[]}));
  for(const round of [1,2])put(root,`finalists/${id}/gap-plans/round-${round}.json`,JSON.stringify({candidate_id:id,contract_sha256:contractHash,round,jobs:[]}));
  const report=`finalists/${id}/problem-report.md`; const manifest={schema_version:'1.0.0',contract_sha256:contractHash,next_skill:'sandbox-hypothesis-stress-test',mount_one_brief_per_run:true,authorization_limits:['offline'],finalists:[{candidate_id:id,decision:'evidence-insufficient',report_path:report,report_sha256:hash(path.join(root,report)),evidence_vector:Object.fromEntries(['G1','G2','G3','G4','G5','G6','G7','G8'].map(g=>[g,'C'])),hard_red_line_findings:[],targeted_jobs:{round_1:0,round_2:0},unresolved_gaps:['unknown']} ]}; mutator?.(root,manifest); put(root,'handoff-manifest.json',JSON.stringify(manifest)); return root; }
const good=fixture(); const duplicate=fixture((root)=>{const p=path.join(root,'finalists/example/reviews/final.json'),r=JSON.parse(fs.readFileSync(p));r.cells[7].gate='G7';fs.writeFileSync(p,JSON.stringify(r));}); const over=fixture((root)=>put(root,'finalists/example/gap-plans/round-2.json',JSON.stringify({candidate_id:'example',contract_sha256:'x',round:2,jobs:[{},{},{}]})));
for(const [root,shouldPass,needle] of [[good,true,'VALID'],[duplicate,false,'exactly G1-G8'],[over,false,'plan identity/hash/budget invalid']]){const r=spawnSync(process.execPath,[validator,root],{encoding:'utf8'});if((r.status===0)!==shouldPass||!(r.stdout+r.stderr).includes(needle))throw new Error(`unexpected validator result: ${r.stdout}${r.stderr}`);} console.log('3 tests passed');
