#!/usr/bin/env node
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
const here=path.dirname(new URL(import.meta.url).pathname),skill=path.resolve(here,'..'),validator=path.join(skill,'scripts/validate.mjs');
const gates=['G1','G2','G3','G4','G5','G6','G7','G8'],dimensions=['customer_user','payer_authority','trigger_cadence','first_value_job_outcome','inputs_data_rights','workflow_output','acquisition_channel','economics_continuing_burden','dependencies_permissions_risk'];
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const put=(root,rel,data='fixture\n')=>{const p=path.join(root,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,data);};const json=(root,rel)=>JSON.parse(fs.readFileSync(path.join(root,rel)));const writeJson=(root,rel,x)=>put(root,rel,JSON.stringify(x));
function fixture(mutator){const root=fs.mkdtempSync(path.join(os.tmpdir(),'problem-discovery-')),ids=['example','other'];fs.cpSync(path.join(skill,'assets/gate-contract-v1.json'),path.join(root,'gate-contract.json'));const contractHash=hash(path.join(root,'gate-contract.json'));
  for(const d of ['raw','territories','archive','aggregate','reports','selected','failures/quarantine','finalists/example/attempts'])fs.mkdirSync(path.join(root,d),{recursive:true});put(root,'raw/source','fixture source\n');put(root,'raw/attempt-history.jsonl',JSON.stringify({record_id:'attempt-example',record_type:'absence-of-attempt',status:'no-attempt-recorded'})+'\n');put(root,'raw/archive-a','archive a\n');put(root,'raw/archive-b','archive b\n');
  const spec={contract_sha256:contractHash,output_path:root,raw_sources:[{original_path:'/fixture/source',delivered_path:'raw/source',sha256:hash(path.join(root,'raw/source'))}],archive_mounted:true,integration_authorized:false};writeJson(root,'run-spec.json',spec);put(root,'rejection-ledger.jsonl','{}\n');
  const finding=(id,claimId,assigned_gates=gates,state='C',evidence_basis='investigative-result')=>({candidate_id:id,claim_id:claimId,lane:'optional',proposition:'test',assigned_gates,attempt_log:evidence_basis==='absence-of-attempt-record'?[]:[{date:'2026-07-18',query_or_action:'offline check',locator:'raw/source:L1',result:'unknown'}],source_classes:evidence_basis==='absence-of-attempt-record'?[]:['fixture'],access_limits:['offline'],citations:['raw/source:L1'],evidence_state:state,evidence_basis,bounded_result:'bounded unknown',missing_proposition:'missing',round:0});
  for(const id of ids)put(root,`territories/${id}.jsonl`,JSON.stringify(finding(id,`claim-${id}`))+'\n');
  const scores={pain_magnitude_recurrence:0,evidence_strength:0,channel_accessibility:0,pilot_clarity:0,competitive_stagnation_whitespace:0,implementation_burden:0,continuing_manual_burden:0},basis=id=>({claim_ids:[`claim-${id}`],citations:['raw/source:L1']}),barrier=id=>({assessment:'bounded unknown',claim_ids:[`claim-${id}`],citations:['raw/source:L1'],strong_builder_prior_applied:false,hard_red_line_id:null});
  const candidate=id=>({candidate_id:id,territory:'fixture',customer:'c',payer:'p',trigger_event:'t',problem:'p',first_value_workflow:'w',citations:['raw/source:L1'],scores:{...scores},score_basis:Object.fromEntries(Object.keys(scores).map(k=>[k,basis(id)])),competitive_stagnation:{basis_class:'unknown',claim_ids:[`claim-${id}`],citations:[]},barrier_decomposition:Object.fromEntries(['build_complexity','external_permissions_data','expert_judgment','procurement_channel','continuing_manual_burden','unit_economics'].map(k=>[k,barrier(id)]))});put(root,'candidates.jsonl',ids.map(id=>JSON.stringify(candidate(id))).join('\n')+'\n');
  const records=[{archive_candidate_id:'arc-a',record_type:'candidate',status:'active',source_path:'raw/archive-a',source_sha256:hash(path.join(root,'raw/archive-a'))},{archive_candidate_id:'arc-b',record_type:'track',status:'archived',source_path:'raw/archive-b',source_sha256:hash(path.join(root,'raw/archive-b'))}],inventoryDigest=digest(records);writeJson(root,'archive/inventory.json',{schema_version:'1.0.0',archive_mounted:true,inventory_digest:inventoryDigest,records});
  const dims=label=>Object.fromEntries(dimensions.map(x=>[x,label])),comparisons=ids.map((id,k)=>({candidate_id:id,comparison_id:`comparison-${id}`,inventory_digest:inventoryDigest,dimension_results:dims('candidate'),neighbors:[{archive_candidate_id:'arc-a',distance:k+1,is_nearest:true,dimension_results:dims('different')},{archive_candidate_id:'arc-b',distance:k+2,is_nearest:false,dimension_results:dims('different')}]}));writeJson(root,'archive/comparisons.json',{archive_mounted:true,dimensions,comparisons});
  let prior=null;const novelty=ids.map((id,i)=>{const x={record_id:`novelty-${i+1}`,sequence:i+1,recorded_at:`2026-07-18T00:0${i}:00Z`,candidate_id:id,comparison_ref:`comparison-${id}`,inventory_digest:inventoryDigest,neighbors:['arc-a'],outcome:'keep',mechanism_delta:'distinct mechanism',basis:'nine dimensions',prior_decision_digest:prior};prior=digest(x);return x;});put(root,'archive/novelty-decisions.jsonl',novelty.map(JSON.stringify).join('\n')+'\n');
  const transitions=ids.flatMap((id,i)=>[{record_id:`transition-${id}-1`,candidate_id:id,occurred_at:`2026-07-18T01:0${i}:00Z`,from:null,to:'proposed',cause:'claim-supported proposal',claim_ids:[`claim-${id}`],citations:['raw/source:L1']},{record_id:`transition-${id}-2`,candidate_id:id,occurred_at:`2026-07-18T02:0${i}:00Z`,from:'proposed',to:'evidence-insufficient',cause:'bounded evidence remains unknown',claim_ids:[`claim-${id}`],citations:['raw/source:L1']}]);put(root,'selection-transitions.jsonl',transitions.map(JSON.stringify).join('\n')+'\n');
  writeJson(root,'aggregate/diversity-matrix.json',{dimensions,adjacency_threshold:7,pairs:[{candidate_a:'example',candidate_b:'other',identical_dimensions:[],adjacent:false,disposition:'retain'}]});
  for(const id of ids){const report=`reports/${id}.md`;put(root,report,'evidence line\n');const sections=Object.fromEntries(['negative_searches','competitors_alternatives','claim_linked_reasoning','transition_history','reconsideration_evidence'].map(k=>[k,[`${report}:L1`]]));const att={candidate_id:id,report_path:report,finding_ids:[`claim-${id}`],transition_record_ids:[`transition-${id}-2`],sections};if(id==='example')att.finalist_sections=Object.fromEntries(['decision','actors_workflow','pain_cadence','attempts','claims','alternatives_stagnation','constraints','risks','unknowns','decision_logic','provenance','optional_depth'].map(k=>[k,[`${report}:L1`]]));writeJson(root,`reports/${id}.attestation.json`,att);}
  const catalog={schema_version:'1.0.0',integration_status:'not-integrated',candidates:ids.map(id=>({candidate_id:id,report_path:`reports/${id}.md`,report_sha256:hash(path.join(root,`reports/${id}.md`)),report_attestation_path:`reports/${id}.attestation.json`,disposition:'evidence-insufficient',external_identities:[],archive_neighbors:['arc-a'],repository_recommendation:'create'}))};writeJson(root,'catalog.json',catalog);
  const id='example',base=`finalists/${id}`;put(root,`${base}/problem-report.md`,'finalist report\n');writeJson(root,`${base}/index.json`,{candidate_id:id,contract_sha256:contractHash,normalized_score:0});const laneGates={customer:['G4','G6','G7','G8'],market:['G4'],competitor:['G2'],technical:['G1','G5'],risk:['G3']};for(const [lane,assigned_gates] of Object.entries(laneGates))put(root,`${base}/avenues/${lane}.jsonl`,JSON.stringify({...finding(id,`claim-${lane}`,assigned_gates),lane})+'\n');
  const cells=gates.map(g=>({gate:g,state:'C',basis:'bounded investigation',evidence_basis:'investigative-result',claim_ids:['claim-example'],citations:['raw/source:L1'],missing_proposition:'missing'})),review={candidate_id:id,contract_sha256:contractHash,cells,decision:'evidence-insufficient',hard_red_line_findings:[]};for(const name of ['initial','post-round-1','final'])writeJson(root,`${base}/reviews/${name}.json`,review);for(const round of [1,2]){const source=`${base}/reviews/${round===1?'initial':'post-round-1'}.json`;writeJson(root,`${base}/gap-plans/round-${round}.json`,{candidate_id:id,contract_sha256:contractHash,round,source_review_path:source,source_review_sha256:hash(path.join(root,source)),jobs:[]});}
  const finalistReport=`${base}/problem-report.md`;writeJson(root,'handoff-manifest.json',{schema_version:'1.0.0',contract_sha256:contractHash,next_skill:'sandbox-hypothesis-stress-test',mount_one_brief_per_run:true,authorization_limits:['offline'],finalists:[{candidate_id:id,reevaluated:true,decision:'evidence-insufficient',report_path:finalistReport,report_sha256:hash(path.join(root,finalistReport)),evidence_vector:Object.fromEntries(gates.map(g=>[g,'C'])),hard_red_line_findings:[],targeted_jobs:{round_1:0,round_2:0},unresolved_gaps:['unknown']}]});
  const reviewLedger=['initial','post-round-1','final'].map((name,i)=>({artifact:`${base}/reviews/${name}.json`,action:'independent-review',status:'accepted',attempt:1,execution_mode:'local',producer_role:'independent-reviewer',independence_attested:true,accepted_at:`2026-07-18T0${3+i}:00:00Z`,sha256:hash(path.join(root,`${base}/reviews/${name}.json`))}));put(root,'execution-ledger.jsonl',[{artifact:'gate-contract.json',action:'freeze',status:'accepted',attempt:1,execution_mode:'local-copy'},...reviewLedger].map(JSON.stringify).join('\n')+'\n');put(root,'REPORT.md','report\n');put(root,'SUMMARY.md','summary\n');
  mutator?.(root);const artifacts=['catalog.json','handoff-manifest.json','archive/inventory.json','archive/comparisons.json','archive/novelty-decisions.jsonl','aggregate/diversity-matrix.json','selection-transitions.jsonl'].map(p=>({path:p,sha256:hash(path.join(root,p))}));writeJson(root,'bundle-manifest.json',{schema_version:'1.0.0',bundle_id:'fixture-bundle',created_at:'2026-07-18T00:00:00Z',immutable:true,contract_sha256:contractHash,catalog_path:'catalog.json',catalog_sha256:hash(path.join(root,'catalog.json')),artifacts});return root;}
const cases=[['valid',null,true,'VALID'],
 ...[['absence lower','absence-only',0],['absence upper','absence-only',1],['exact lower','exact-job-mismatch',2],['exact upper','exact-job-mismatch',3],['longitudinal lower','longitudinal-unresolved',4],['longitudinal upper','longitudinal-unresolved',5]].map(([name,basisClass,score])=>[name,r=>{const p=path.join(r,'candidates.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[1].competitive_stagnation={basis_class:basisClass,claim_ids:['claim-other'],citations:score?['raw/source:L1']:[]};x[1].scores.competitive_stagnation_whitespace=score;put(r,'candidates.jsonl',x.map(JSON.stringify).join('\n')+'\n');},true,'VALID']),
 ['valid history-unknown D',r=>{const p=path.join(r,'finalists/example/avenues/customer.jsonl'),x=JSON.parse(fs.readFileSync(p));x.evidence_state='D';x.evidence_basis='absence-of-attempt-record';x.attempt_log=[];x.source_classes=[];x.citations=['raw/attempt-history.jsonl:record-attempt-example'];put(r,'finalists/example/avenues/customer.jsonl',JSON.stringify(x)+'\n');},true,'VALID'],
 ['history D rejects market line',r=>{const p=path.join(r,'finalists/example/avenues/customer.jsonl'),x=JSON.parse(fs.readFileSync(p));x.evidence_state='D';x.evidence_basis='absence-of-attempt-record';x.attempt_log=[];x.source_classes=[];x.citations=['raw/source:L1'];put(r,'finalists/example/avenues/customer.jsonl',JSON.stringify(x)+'\n');},false,'must cite a matching structured record'],
 ['empty C finding citation',r=>{const p=path.join(r,'territories/other.jsonl'),x=JSON.parse(fs.readFileSync(p));x.citations=[];put(r,'territories/other.jsonl',JSON.stringify(x)+'\n');},false,'C finding requires resolving citation'],
 ['empty investigative D citation',r=>{const p=path.join(r,'finalists/example/avenues/customer.jsonl'),x=JSON.parse(fs.readFileSync(p));x.evidence_state='D';x.evidence_basis='investigative-result';x.citations=[];put(r,'finalists/example/avenues/customer.jsonl',JSON.stringify(x)+'\n');},false,'D finding requires resolving citation'],
 ['empty C gate citation',r=>{const x=json(r,'finalists/example/reviews/final.json');x.cells[0].citations=[];writeJson(r,'finalists/example/reviews/final.json',x);},false,'gate state C requires resolving citation'],
 ['invented score claim',r=>{const p=path.join(r,'candidates.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[0].score_basis.pilot_clarity.claim_ids=['invented'];put(r,'candidates.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'finding claim ID does not resolve'],
 ['invented gate claim',r=>{const p=path.join(r,'finalists/example/reviews/final.json'),x=json(r,'finalists/example/reviews/final.json');x.cells[0].claim_ids=['invented'];writeJson(r,'finalists/example/reviews/final.json',x);},false,'finding claim ID does not resolve'],
 ['invented report claim',r=>{const x=json(r,'reports/other.attestation.json');x.finding_ids=['invented'];writeJson(r,'reports/other.attestation.json',x);},false,'finding claim ID does not resolve'],
 ['invented barrier claim',r=>{const p=path.join(r,'candidates.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[0].barrier_decomposition.unit_economics.claim_ids=['invented'];put(r,'candidates.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'finding claim ID does not resolve'],
 ['invented transition claim',r=>{const p=path.join(r,'selection-transitions.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[0].claim_ids=['invented'];put(r,'selection-transitions.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'finding claim ID does not resolve'],
 ['duplicate candidate ID',r=>{const p=path.join(r,'candidates.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[1].candidate_id=x[0].candidate_id;put(r,'candidates.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'unique before indexing'],
 ['inventory omission',r=>{const x=json(r,'archive/comparisons.json');x.comparisons[0].neighbors.pop();writeJson(r,'archive/comparisons.json',x);},false,'every archive inventory record'],
 ['inventory type',r=>{const x=json(r,'archive/inventory.json');x.records[0].record_type='junk';writeJson(r,'archive/inventory.json',x);},false,'enum schema failure'],
 ['nearest marker',r=>{const x=json(r,'archive/comparisons.json');x.comparisons[0].neighbors[1].is_nearest=true;writeJson(r,'archive/comparisons.json',x);},false,'nearest-neighbor marker'],
 ['novelty ref',r=>{const p=path.join(r,'archive/novelty-decisions.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[0].comparison_ref='missing';put(r,'archive/novelty-decisions.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'comparison_ref'],
 ['novelty neighbor',r=>{const p=path.join(r,'archive/novelty-decisions.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[0].neighbors=['arc-b'];put(r,'archive/novelty-decisions.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'nearest neighbors'],
 ['novelty chain',r=>{const p=path.join(r,'archive/novelty-decisions.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[1].prior_decision_digest='wrong';put(r,'archive/novelty-decisions.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'append-only'],
 ['transition evidence',r=>{const p=path.join(r,'selection-transitions.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[0].citations=[];put(r,'selection-transitions.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'too few items'],
 ['transition chain',r=>{const p=path.join(r,'selection-transitions.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[1].from='investigating';put(r,'selection-transitions.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'broken selection'],
 ['catalog disposition',r=>{const x=json(r,'catalog.json');x.candidates[1].disposition='reject';writeJson(r,'catalog.json',x);},false,'catalog disposition'],
 ...[['exact low','exact-job-mismatch',1],['exact high','exact-job-mismatch',4],['longitudinal low','longitudinal-unresolved',3],['absence high','absence-only',2],['unknown high','unknown',1]].map(([name,basisClass,score])=>[name,r=>{const p=path.join(r,'candidates.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[0].competitive_stagnation.basis_class=basisClass;x[0].scores.competitive_stagnation_whitespace=score;put(r,'candidates.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'anchor range']),
 ['unsupported stagnation',r=>{const p=path.join(r,'candidates.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[0].competitive_stagnation={basis_class:'exact-job-mismatch',claim_ids:[],citations:[]};x[0].scores.competitive_stagnation_whitespace=2;put(r,'candidates.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'unsupported'],
 ['external ID collision',r=>{const x=json(r,'catalog.json');x.candidates[0].external_identities=[{identity_type:'track-id',value:'other',source:'archive'}];writeJson(r,'catalog.json',x);},false,'collides'],
 ['diversity dimension',r=>{const x=json(r,'aggregate/diversity-matrix.json');x.pairs[0].identical_dimensions=['bogus'];writeJson(r,'aggregate/diversity-matrix.json',x);},false,'unknown mechanism'],
 ['duplicate pair',r=>{const x=json(r,'aggregate/diversity-matrix.json');x.pairs.push({...x.pairs[0],candidate_a:'other',candidate_b:'example'});writeJson(r,'aggregate/diversity-matrix.json',x);},false,'pairs must be unique'],
 ['waiver evidence',r=>{const x=json(r,'aggregate/diversity-matrix.json');x.adjacency_threshold=0;x.pairs[0].adjacent=true;x.pairs[0].disposition='waiver';x.pairs[0].waiver_reason='different';writeJson(r,'aggregate/diversity-matrix.json',x);},false,'evidence-backed'],
 ['report section',r=>{const x=json(r,'reports/other.attestation.json');x.sections.negative_searches=[];writeJson(r,'reports/other.attestation.json',x);},false,'lacks resolvable evidence'],
 ['finalist sections',r=>{const x=json(r,'reports/example.attestation.json');delete x.finalist_sections;writeJson(r,'reports/example.attestation.json',x);},false,'richer structured'],
 ['builder prior',r=>{const p=path.join(r,'candidates.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[0].barrier_decomposition.unit_economics.strong_builder_prior_applied=true;put(r,'candidates.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'only to build_complexity'],
 ['red line',r=>{const p=path.join(r,'candidates.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x[0].barrier_decomposition.external_permissions_data.hard_red_line_id='ordinary-privacy';put(r,'candidates.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'not frozen'],
 ['out of order review',r=>{const p=path.join(r,'execution-ledger.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x.find(e=>e.artifact.endsWith('initial.json')).accepted_at='2026-07-18T06:00:00Z';put(r,'execution-ledger.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'temporal order'],
 ['non-independent review',r=>{const p=path.join(r,'execution-ledger.jsonl'),x=fs.readFileSync(p,'utf8').trim().split('\n').map(JSON.parse);x.find(e=>e.artifact.endsWith('initial.json')).independence_attested=false;put(r,'execution-ledger.jsonl',x.map(JSON.stringify).join('\n')+'\n');},false,'independent temporal'],
 ['targeted finding before provenance',r=>{const p=path.join(r,'finalists/example/avenues/customer.jsonl'),x=JSON.parse(fs.readFileSync(p));x.round=1;put(r,'finalists/example/avenues/customer.jsonl',JSON.stringify(x)+'\n');},false,'finding acceptance lacks post-review'],
 ['authorization only',r=>{const s=json(r,'run-spec.json');s.integration_authorized=true;writeJson(r,'run-spec.json',s);const c=json(r,'catalog.json');c.integration_status='integrated';writeJson(r,'catalog.json',c);},false,'authorization, contract'],
 ['bogus contract',r=>{const s=json(r,'run-spec.json');s.integration_authorized=true;s.integration_contract={path:'integration/missing.json',sha256:'x'};s.integration_completion_path='integration/completed.json';writeJson(r,'run-spec.json',s);const c=json(r,'catalog.json');c.integration_status='integrated';writeJson(r,'catalog.json',c);writeJson(r,'integration/completed.json',{schema_version:'1.0.0',contract_path:'integration/missing.json',contract_sha256:'x',actions:[]});},false,'missing/empty file'],
 ['integration hash',r=>{put(r,'integration/contract.txt','contract\n');put(r,'integration/output.txt','done\n');const s=json(r,'run-spec.json');s.integration_authorized=true;s.integration_contract={path:'integration/contract.txt',sha256:'wrong'};s.integration_completion_path='integration/completed.json';writeJson(r,'run-spec.json',s);writeJson(r,'integration/completed.json',{schema_version:'1.0.0',contract_path:'integration/contract.txt',contract_sha256:'wrong',actions:[{action_id:'a',action:'write',completed_at:'2026-07-18T01:00:00Z',status:'completed',artifact_path:'integration/output.txt',artifact_sha256:hash(path.join(r,'integration/output.txt'))}]});const c=json(r,'catalog.json');c.integration_status='integrated';writeJson(r,'catalog.json',c);},false,'contract hash mismatch'],
 ['no integration actions',r=>{put(r,'integration/contract.txt','contract\n');const h=hash(path.join(r,'integration/contract.txt')),s=json(r,'run-spec.json');s.integration_authorized=true;s.integration_contract={path:'integration/contract.txt',sha256:h};s.integration_completion_path='integration/completed.json';writeJson(r,'run-spec.json',s);writeJson(r,'integration/completed.json',{schema_version:'1.0.0',contract_path:'integration/contract.txt',contract_sha256:h,actions:[]});const c=json(r,'catalog.json');c.integration_status='integrated';writeJson(r,'catalog.json',c);},false,'too few items']];
let passed=0;for(const [name,mutator,shouldPass,needle] of cases){const root=fixture(mutator);const r=spawnSync(process.execPath,[validator,root],{encoding:'utf8'}),output=r.stdout+r.stderr;if((r.status===0)!==shouldPass||!output.includes(needle))throw new Error(`${name}: unexpected validator result\n${output}`);passed++;}console.log(`${passed} tests passed`);
