name: govulncheck

on:
  push:
  schedule:
    - cron: '17 2 * * *'

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee  # v1.0.4
        with:
          go-version-file: go.mod
          go-package: ./...
          output-format: sarif
          output-file: govulncheck.sarif
      - name: Upload SARIF to GitHub code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@e46ed2cbd01164d986452f91f178727624ae40d7  # v4.35.3
        with:
          sarif_file: govulncheck.sarif
